# Generated by Django 4.2.16 on 2024-10-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(db_column='logo', default='./core/static/core_ui/image/logoCriste.png', upload_to=''),
            preserve_default=False,
        ),
    ]
