# Generated by Django 4.2.16 on 2024-10-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.ImageField(db_column='background', default='', upload_to=''),
            preserve_default=False,
        ),
    ]
