# Generated by Django 4.2.16 on 2024-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='animation_video',
            field=models.ImageField(db_column='animation_video', default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='background',
            field=models.ImageField(db_column='background', default='', upload_to=''),
            preserve_default=False,
        ),
    ]
